### ISSUE TITLE
Bug: Infinite loop blocking main thread when password fills the width of the label.

### ISSUE THREAD

**Issue by minuscorp** [EurekaCommunity/GenericPasswordRow#7] opened 2017-06-02 13:11 UTC
The title is pretty descriptive, but the issue is pretty easy to reproduce, just create a GenericPasswordRow with a customized password validator. When you try to type the password and it's long enough to fill the width of the field, main thread gets stuck, see traceback and screenshots below:

**Form:**
```swift
<<< GenericPasswordRow("user_password"){
  row in
  row.passwordValidator = CustomPasswordValidator()
  row.placeholder = NSLocalizedString("Password", comment: "Password")
  let passwordValidation = RuleClosure<String> { rowValue in
    return ((rowValue == nil) || !(self.form.values()["user_mail"] as? String == rowValue.value)) ? ValidationError(msg: NSLocalizedString("Wrong Password", comment: "Wrong Password Mail")) : nil
  }
  row.add(rule: passwordValidation)
}
```

**Validator:**
```swift
class CustomPasswordValidator: PasswordValidator {
    
    fileprivate struct PasswordRule {
        
        let hint: String
        let test: (String) -> Bool
    }
    
    open let maxStrength = 5.0
    
    fileprivate let rules: [PasswordRule] = [
        PasswordRule(hint: "Please enter a lowercase letter") { $0.satisfiesRegexp("[a-z]") },
        PasswordRule(hint: "Please enter a number or a special character") { $0.satisfiesRegexp("(?=.*([0-9]|[^\\w]))") },
        PasswordRule(hint: "Please enter an uppercase letter") { $0.satisfiesRegexp("[A-Z]") },
        PasswordRule(hint: "At least 8 characters") { $0.characters.count > 7 },
        PasswordRule(hint: "No more than two consecutive repeating characters or numbers") { $0.satisfiesRegexp("^(?!.*(.)\\1{1})") }
        
    ]
    
    internal func strengthForPassword(_ password: String) -> Double {
        return rules.reduce(0) { $0 + ($1.test(password) ? 1 : 0) }
    }
    
    internal func hintForPassword(_ password: String) -> String? {
        return rules.reduce([]) { $0 + ($1.test(password) ? []: [$1.hint]) }.first
    }
    
    internal func isPasswordValid(_ password: String) -> Bool {
        return rules.reduce(true) { $0 && $1.test(password) }
    }
    
    internal func colorsForStrengths() -> [Double: UIColor] {
        return [
            0: UIColor(red: 244 / 255, green: 67 / 255, blue: 54 / 255, alpha: 1),
            1: UIColor(red: 255 / 255, green: 193 / 255, blue: 7 / 255, alpha: 1),
            2: UIColor(red: 3 / 255, green: 169 / 255, blue: 244 / 255, alpha: 1),
            3: UIColor(red: 153 / 255, green: 255 / 255, blue: 153 / 255, alpha: 1),
            4: UIColor(red: 139 / 255, green: 195 / 255, blue: 74 / 255, alpha: 1)
        ]
    }
    
}

extension String {
    
    func satisfiesRegexp(_ regexp: String) -> Bool {
        return range(of: regexp, options: .regularExpression) != nil
    }
    
}

```
**Main Thread Stack:**
![MainThreadStack](https://cloud.githubusercontent.com/assets/3819883/26727032/7a5a7120-47a5-11e7-9aeb-0e8717f8edac.png)

**Stuck at:**
[Here!](https://github.com/EurekaCommunity/GenericPasswordRow/blob/master/Sources/GenericPasswordCell.swift#L90)

P.D.: Commenting out both `beginUpdates()` and `endUpdates()` do not fix the issue, getting stuck at an unknown traceable point of execution.

EDIT: It seems that something that I can't properly debug allocates (after 30 seconds of blocking the Main Thread as I described) up to 1GB of RAM before getting:
`Message from debugger: Terminated due to memory issue`

**Comment by dernster** [comment] 2017-06-03 16:55
@minuscorp Hey! Thanks for reporting this. Can you provide a clonable-repo example with this? I tried and couldn't reproduce. Which version of Xcode are you using?

**Comment by minuscorp** [comment] 2017-06-03 17:22
For some reason, in release builds I can't make this happen, I was trying to send you a video of the issue... On Monday I'll try to make a project to reproduce this... 🤔

**Comment by dernster** [comment] 2017-06-23 13:34
@minuscorp Any update on this? Otherwise I'll be closing this issue since I cannot reproduce it.

**Comment by minuscorp** [comment] 2017-06-23 14:02
I could not reproduce this issue under any other circumstances outside my project and it seems to affect only to Xcode installed builds so I think this can be closed by now.

Sorry for the delay.

**Comment by dernster** [comment] 2017-06-23 14:41
@minuscorp Cool, just re-open this issue whenever you think it's appropriate.

**Closed as completed by dernster** 2017-06-23 14:41 UTC
